### PR TITLE
Basepage.html template bootstrap

### PR DESCRIPTION
**Pull request by whoo**
Hi,

I've just write a page based on bootstap template.
- http://getbootstrap.com/
- http://bootswatch.com/darkly/

### CODE REVIEW

**Comment by oetiker** [comment]
do you have a screenshot of how this looks ?

**Comment by whoo** [comment]
Hi Tobias,

I've just uploaded images on imagebin.ca
I know that there is a new project with new reporting, but templates are more simple to implement for my basics skills :)

>> http://imagebin.ca/v/2V0raZFMrAEE (normal size)
Image of bootstrap
>> http://imagebin.ca/v/2V0ryIPzpAlG (full page)
Image of bootstrap

**Comment by oetiker** [comment]
hmm ... I think when doing a bootstrap switch the integration should be more tight ... like also the menu being in bootstrap style ...

**Comment by oetiker** [comment]
superseeded bu #87

**Pull request closed without merging**
