### PR TITLE
add scrollbar for overflow

### PR DESCRIPTION
**Pull request by bevhost**

### CODE REVIEW

**Comment by oetiker** [comment]
thanks

**Comment by dekenberg** [comment]
I just got around to updating my instance and I found the sidebar's alignment is incorrect when there isn't a need for a scroll bar. This PR always makes the sidebars visible which then messes up the alignment. I think setting .sidebar-menu overflow-x to auto would be a better choice, since when a horizontal scroll bar isn't needed it remains hidden.

**Comment by bevhost** [comment]
I agree, I wasn't able to get it to do that.  My CSS isn't great.  I got it good enough to work for me.
Without the scrollbar, the items on the end of the menu disappear off the screen and cannot be selected.
I also had a problem with the images being too wide for the sidebar menu and one sitting below the other behind the select dropbox.

**Comment by dekenberg** [comment]
When you get a minute - can you test to see if this works for your case? on smokeping-screen.css change the value of overflow-x from hidden to auto (line 57) and then delete line 33?

**Comment by bevhost** [comment]
Yes, works much better thanks.
see https://github.com/oetiker/SmokePing/pull/182
I also worked out how to stop the RRDtool Image from wrapping by moving it back down the bottom like it was in earlier versions

**Pull request merged**
