### PR TITLE
add probes

### PR DESCRIPTION
**Pull request by slesru**
Hello!

There are 3 probes here

### CODE REVIEW

**Comment by oetiker** [comment]
thanks for your contribution ... your  modules seem to be based on other modules already in the repo, often adding ssh as a transport ... have you investigated, adding extra options to the existing modules to minimaze redundancy ?

**Comment by slesru** [comment]
Hello!

Honestly, no, I did not think about adding extra options. I just need to solve my problems and wanted to share result :-)

Thank you!

**Comment by oetiker** [comment]
so when someone fixes a problem with the original probe he would have to fix yours too, because you did not integrate your changes into the original probe ?

**Comment by slesru** [comment]
ok, no then no.
thank you!

**Pull request closed without merging**
