### PR TITLE
Changes POST action to correctly reflected generated URL

### PR DESCRIPTION
**Pull request by dekenberg**
Uses JQuery to rewrite the request action to the variables that were submitted via the form. This changes the URL to accurately reflect the generated graph. This fixes the issue discussed in #173

### CODE REVIEW

**Comment by dekenberg** [comment]
@oetiker When you get a minute can you review and merge?

**Comment by oetiker** [comment]
looking good ... sorry missed that one

**Comment by oetiker** [comment]
if you are in the mood: https://tobi.oetiker.ch/smokenav/

should be simple to add via https://github.com/oetiker/RrdGraphJS

**Comment by dekenberg** [comment]
Thanks! Sounds good - I will take a deeper dive into that later. I already have a patch written for a cropper fix so I want to get that one out first.

**Pull request merged**
