### PR TITLE
Improve mobile support

### PR DESCRIPTION
**Pull request by nschermer**
- It now is usable on mobile phones
- Various speed optimizations (...according to google, for mobile devices)
- Moved css to separate file(s)
- Css print support
- Html5 valid (remove pragma's, we set no-cache on the header in the code and this is more a nginx/apache thing for images, add alt for images to avoid warning and drop the border=0.

### CODE REVIEW

**Comment by oetiker** [comment]
@nschermer did you see my comment regarding https://github.com/oetiker/RrdGraphJS in your previous PR?

**Comment by nschermer** [comment]
Yes I read it, but I think its better to finish this first and later look at other JS code.

**Comment by oetiker** [comment]
are you happy now with your code ?

**Comment by nschermer** [comment]
It seems to work ok, so yeah. I currently don't have time to look into the
alternative js graphs tho.

Nick

**Comment by moetiker** [comment]
@nschermer if I have a select a single graph on the mobile phone (ios on chome). the menubar goes under the graph and should go over the graph ...

**Pull request merged**
